project:
  type: website
  output-dir: docs      # GitHub Pages will serve from /docs

search: false

website:
  title: "Vikesh Dheeriya"
  google-analytics: G-NG9FX3NQD3
  navbar:
    left:
      - text: about me
        href: about.qmd
      - text: portfolio
        href: projects.qmd  
      - text: viks veggies
        href: viksveggies.qmd

format:
  html:
    theme: flatly
    css: styles.css
    allow-html: true    # needed for our custom HTML
    toc: true           # default; can override in individual pages

editor: visual
