project:
  type: website
  output-dir: docs

website:
  title: "vikeshdh.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - hobbies.qmd
      - Resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

