project:
  type: website
  output-dir: docs            # directory GitHub Pages will serve
search: false
website:
  title: "Vikesh Dheeriya"
  navbar:
    left:
      - text: home
        href: index.qmd
      - text: about me
        href: about.qmd
      - text: portfolio
        href: projects.qmd
      - text: resume
        href: Vikesh_Dheeriya_Resume.pdf
      - text: cooking
        href: hobbies.qmd

format:
  html:
    allow-html: true
    theme: flatly
    css: styles.css       
    toc: true

editor: visual
