project:
  type: website
  output-dir: docs      # GitHub Pages will serve from /docs

search: false

website:
  title: "Vikesh Dheeriya"
  google-analytics: "G-NG9FX3NQD3"
  navbar:
    left:
      - text: About Me
        href: about.qmd
      - text: Portfolio
        href: projects.qmd  
      - text: Viks Veggies
        href: viksveggies.qmd

format:
  html:
    theme: flatly
    css: styles.css
    allow-html: true    # needed for our custom HTML
    toc: true           # default; can override in individual pages

editor: visual
