project:
  type: website
  output-dir: docs

search: false

website:
  title: "Vikesh Dheeriya"
  google-analytics: "G-NG9FX3NQD3"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Portfolio
        href: portfolio.qmd

format:
  html:
    theme: flatly
    css: styles.css
    allow-html: true
    toc: false
    mainfont: Nunito
